VIH-7436 edit hearing start time
hmcts/vh-admin-web pull request #638
Opened 2021-03-12 09:22 UTC by surfsquid

https://tools.hmcts.net/jira/browse/VIH-7436

Changes to other_information property in hearing to send and receive data as a pipe delimited string

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[X] No
```

2021-03-12 09:23 UTC, npoxon requested changes
Please don't merge this without AC tests

2021-03-12 09:30 UTC, levibutler approved these changes
Nice :)
Nick would like to wait for AC tests tho please

2021-03-12 15:06 UTC, npoxon submitted a review, later dismissed
LGTM

2021-03-15 09:50 UTC, levibutler commented on AdminWebsite/AdminWebsite/ClientApp/src/app/services/pipe-stringifier.service.spec.ts
> +        expect(service.decode(testString)).toEqual(testObject);
could we test a couple more not so happy paths?
`|name||height|100` // With empty
`|name|null|height|100` // With null
`|prop1|1|prop2|2|prop3|3` // 3 properties in values should parse to string
`|name|test|height|` // missing height
`|otherinfo|containingapipe|likethis`
null or empty

2021-03-15 11:25 UTC, levibutler approved these changes

2021-03-15 12:52 UTC, merged