Fixing eJudiciary email errors for Add Participant
hmcts/vh-admin-web pull request #682
Opened 2021-04-21 15:05 UTC by mulvaneyjHMCTS

### JIRA link (if applicable) ###
VIH-7284

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2021-04-23 08:48 UTC, phillipjchambers commented on AdminWebsite/AdminWebsite/ClientApp/src/app/booking/add-participant/add-participant.component.ts
> +                    } else if (
Do you know why this is using a timeout?

2021-04-26 14:32 UTC, FarronF requested changes

2021-04-26 14:32 UTC, FarronF commented on AdminWebsite/AdminWebsite/ClientApp/src/app/booking/search-email/search-email.component.ts
> +        this.errorNotFoundJohEmail = this.hearingRoleParticipant === 'Panel Member' || this.hearingRoleParticipant === 'Winger';
Change to 
`this.judiciaryRoles.includes(this.hearingRoleParticipant)`

2021-04-26 15:19 UTC, FarronF approved these changes

2021-04-26 16:16 UTC, merged