Feature/vih 7539 automate ejud hearing amend email
hmcts/vh-admin-web pull request #690
Opened 2021-04-29 14:29 UTC by PrasannaDommalapati

### JIRA link (if applicable) ###

https://tools.hmcts.net/jira/browse/VIH-7539

### Change description ###

Added new condition to send an email to a notification Type HearingAmmendmentEjudJoh

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2021-04-29 14:34 UTC, robertbennett1998 submitted a review, later dismissed
LGTM

2021-04-29 14:42 UTC, robertbennett1998 submitted a review, later dismissed

2021-04-29 15:10 UTC, shaed-parkar requested changes
The same params are passed in, you don't need two if blocks to determine the template type

2021-04-29 15:10 UTC, shaed-parkar commented on AdminWebsite/AdminWebsite/Contracts/Requests/BookHearingRequest.cs
> +        public bool IsCourtroomAccount { get; set; }
this needs to be removed

2021-04-29 15:10 UTC, shaed-parkar commented on AdminWebsite/AdminWebsite/Mappers/AddNotificationRequestMapper.cs
> +                notificationType = NotificationType.HearingAmendmentEJudJoh;
because the params sent to the template are the same here, you can use a conditional ternary

2021-04-30 14:55 UTC, robertbennett1998 approved these changes
LGTM. Shaed's changes have been made

2021-05-05 10:00 UTC, closed without merging

2021-05-05 10:00 UTC, PrasannaDommalapati commented
No changes

2021-05-05 10:21 UTC, shaed-parkar commented
This PR's original content has been merged in by another PR