VIH-8471 hearing confirmations incorrectly sent to judge username
hmcts/vh-admin-web pull request #833
Opened 2021-11-22 10:32 UTC by ChrisPaulP

### JIRA link (if applicable) ###

https://tools.hmcts.net/jira/browse/VIH-8471

### Change description ###

Fix for judge receiving emails to incorrect email address. Judge should only receive emails when they have entered an email address. 

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2021-11-22 13:54 UTC, FarronF commented on AdminWebsite/AdminWebsite.UnitTests/Services/HearingServiceTests.cs
> +        { // chris
```suggestion
        {       
```

2021-11-22 13:57 UTC, FarronF commented on AdminWebsite/AdminWebsite.UnitTests/Mappers/NotificationMappers/MapToDemoOrTestNotificationTests.cs
> +                OtherInformation = new OtherInformationDetails { JudgeEmail = "judge@hmcts.net", JudgePhone = "123456789" }.ToOtherInformationString()
Can we assert anything extra on the result from this?

2021-11-22 14:04 UTC, FarronF commented on AdminWebsite/AdminWebsite/Mappers/AddNotificationRequestMapper.cs
> +                if (string.IsNullOrEmpty(judgeEmail)) return null;
```suggestion
                if (string.IsNullOrEmpty(judgeEmail)) 
                {
                    return null;
                }
```

The above is a personal preference of mine maintainability. But we don't have any style guidelines regarding this, so you can leave it if you want. But the following lines should be unindented as at first glance it looks like it's nested inside this.

2021-11-22 14:10 UTC, FarronF commented on AdminWebsite/AdminWebsite/Services/HearingsService.cs
> +            if (notificationRequests.Count < 1) return;
Could we have tests for the mapper returning a null value and if there are no requests that it doesn't call CreateNotifications?

2021-11-25 09:48 UTC, omio-ma approved these changes

2021-11-25 11:46 UTC, FarronF commented on AdminWebsite/AdminWebsite/Mappers/AddNotificationRequestMapper.cs
>                          notificationType = NotificationType.EJudJudgeDemoOrTest;
These lines should be unindented one step

2021-11-25 11:49 UTC, FarronF commented on AdminWebsite/AdminWebsite.UnitTests/Mappers/NotificationMappers/MapToDemoOrTestNotificationTests.cs
> +            const string expectedJudgeEmail = "judge@hmcts.net";
This is the same as the email string on line 23. Could this be defined before that and used to set JudgeEmail there?

2021-11-25 11:59 UTC, FarronF commented on AdminWebsite/AdminWebsite/Mappers/AddNotificationRequestMapper.cs
> +                    if (string.IsNullOrEmpty(judgeEmail))
Do we not want to use the email for the judge account as a fall back? It doesn't seem clear from the ticket so I need clarification on that.

Also it looks like we don't show the judge email field for ejud users so ejud judges will never get an email.

2021-11-25 12:04 UTC, FarronF commented on AdminWebsite/AdminWebsite/Mappers/AddNotificationRequestMapper.cs
> +                    participant.ContactEmail = judgeEmail;
Rather than changing the participant.ContactEmail could we change how we set ContactEmail on the new AddNotificationRequest instead?

2021-11-25 12:16 UTC, FarronF requested changes
See comments. My main concern is handling ejud users if you look at assign-judge.component we don't provide an email field for them. I believe they use their own accounts so we probably want to send an email in that case at least. I've added a comment to the ticket for clarification as maybe I've misunderstood.

2021-11-29 11:40 UTC, FarronF commented on AdminWebsite/AdminWebsite/Mappers/AddNotificationRequestMapper.cs
> +                    }
Should this come before the null check? As judgeEmail will always be null for eJud. Or does the GetJudgeEmail() method handle getting it from the judge participant in that case

2021-11-30 09:13 UTC, FarronF commented on AdminWebsite/AdminWebsite/Mappers/AddNotificationRequestMapper.cs
> +                    if (isEmailEjud)
Correct the indentation here.

2021-11-30 09:26 UTC, FarronF commented on AdminWebsite/AdminWebsite.UnitTests/Services/HearingServiceTests.cs
> +        public async Task EditHearingSendConfirmation_Judge_Should_not_Receive_Call_Without_judge_email_address_when_HearingType_Is_DEMO_for_Confirmedhearing()
I know the previous test was already here but is the name Should_Receive_Call valid?

2021-11-30 10:29 UTC, FarronF approved these changes

2021-11-30 10:57 UTC, omio-ma approved these changes

2021-11-30 10:57 UTC, merged