VIH-8545 send correct email for test demo on edit judge
hmcts/vh-admin-web pull request #835
Opened 2021-12-06 18:31 UTC by ChrisPaulP

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/VIH-8545

### Change description ###
 When editing a generic hearing, the correct test demo email will be sent to judge's

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2021-12-07 15:19 UTC, kevin-hmcts approved these changes
LGTM

2021-12-07 15:50 UTC, PrasannaDommalapati commented on AdminWebsite/AdminWebsite.UnitTests/Services/HearingServiceTests.cs
> +            _mocker.Mock<INotificationApiClient>()
Assert with specific Notification Type rather IsAny Notification Type

2021-12-07 15:51 UTC, ZJianWang approved these changes

2021-12-07 15:52 UTC, PrasannaDommalapati commented on AdminWebsite/AdminWebsite/Controllers/HearingsController.cs
> +                await _hearingsService.ProcessGenericEmail(updatedHearing, updatedHearing.Participants);
its personal preference, Add curly braces for readability.

2021-12-07 15:55 UTC, PrasannaDommalapati commented on AdminWebsite/AdminWebsite.UnitTests/Services/HearingServiceTests.cs
> +            _mocker.Mock<INotificationApiClient>()
Assert with specific Notification Type rather IsAny Notification Type

2021-12-07 15:58 UTC, PrasannaDommalapati requested changes
Added comments

2021-12-07 16:37 UTC, PrasannaDommalapati commented on AdminWebsite/AdminWebsite/Controllers/HearingsController.cs
> +                if (!updatedHearing.HasGenericHearingJudgeChanged(originalHearing))
Could you update this to a positive condition please rather than using !

2021-12-07 16:41 UTC, PrasannaDommalapati commented on AdminWebsite/AdminWebsite/Extensions/HearingDetailsResponseExtensions.cs
> +            var judgeA = hearing.Participants.FirstOrDefault(x =>
could you change the variable names to e.g: originalHearingJudge, newHearingJudge

2021-12-07 16:45 UTC, omio-ma commented on AdminWebsite/AdminWebsite/Extensions/HearingDetailsResponseExtensions.cs
> +            var judgeA = hearing.Participants.FirstOrDefault(x =>
could we rename this to something more appropriate, like judgeA to judgeFromUpdatedHearing and judgeB to judgeFromOriginalHearing

2021-12-07 16:45 UTC, omio-ma commented on AdminWebsite/AdminWebsite/Extensions/HearingDetailsResponseExtensions.cs
> +                   x.UserRoleName.Contains(RoleNames.Judge, StringComparison.CurrentCultureIgnoreCase));
could we move this logic into a private function  as its repeated here

2021-12-08 12:01 UTC, PrasannaDommalapati approved these changes
LGTM

2021-12-08 12:10 UTC, omio-ma approved these changes

2021-12-08 12:16 UTC, merged