VIH-9254 - Add and Remove AAD Redirect URLs
hmcts/vh-admin-web pull request #950
Opened 2022-08-23 15:32 UTC by chris-pateman

### JIRA link (if applicable) ###
VIH-9254

### Change description ###
Add AAD Redirect URL on PR open
Remove AAD Redirect URLs on PR close

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ x ] No
```

2022-08-24 14:03 UTC, v1ferrarij requested changes

2022-08-24 14:03 UTC, v1ferrarij commented on azure-pipelines.sds.pr-close.yml
> +      ref: VIH-9254-redirect-url
needs amending.

2022-08-24 15:37 UTC, chris-pateman commented on azure-pipelines.sds.pr-close.yml
> +      ref: VIH-9254-redirect-url
Completed

2022-08-25 13:27 UTC, v1ferrarij approved these changes

2022-08-25 14:47 UTC, merged